/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c7c6ca",
        "on-secondary-fixed": "#0b1c30",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        primary: "#000000",
        tertiary: "#000000",
        "surface-tint": "#5f5e5f",
        "tertiary-fixed": "#e6e2de",
        "on-surface-variant": "#46474a",
        "inverse-surface": "#2d3133",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#cac6c2",
        "primary-fixed": "#e5e2e3",
        "on-secondary-fixed-variant": "#38485d",
        "surface-bright": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#c8c6c7",
        "on-secondary-container": "#54647a",
        "on-primary-container": "#858384",
        "on-tertiary-fixed": "#1c1b19",
        "on-tertiary-fixed-variant": "#484644",
        error: "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        secondary: "#505f76",
        "secondary-container": "#d0e1fb",
        "primary-fixed-dim": "#c8c6c7",
        background: "#f7f9fb",
        "secondary-fixed": "#d3e4fe",
        "on-primary-fixed": "#1b1b1c",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#76777b",
        "surface-dim": "#d8dadc",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#1b1b1c",
        "surface-variant": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-primary-fixed-variant": "#474647",
        "on-tertiary-container": "#868380",
        "tertiary-container": "#1c1b19",
        "surface-container": "#eceef0",
        surface: "#f7f9fb",
        "on-background": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        "container-margin": "1.5rem",
        "element-padding": "0.5rem",
        "panel-gap": "0.75rem",
        gutter: "1rem",
      },
      fontFamily: {
        "code-snippet": ["monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-mono": ["Space Grotesk", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-snippet": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-mono": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
